### ISSUE TITLE
Segfault on read at the backend that is disabled

### ISSUE THREAD

**Issue by shaitan** [reverbrain/elliptics#613]
Cache read backtrace:
```
#0 0x00007fc08484c4fa in ioremap::cache::cache_manager::read (this=0x7fc063cdcb60, id=0x7fbfb007cee8 "\276K\375\235\247@\270,\263\367Pc?\374\006\231zɘ\252h\341\335\352\234J]\336\365\261\307Je\261\223\335\354\344\263/\263\027\312>\376\362볖\024\016\a%cq\021\311V\232\250n\274k\203", cmd=0x7fbfb007ce30,
io=<optimized out>) at /home/buildfarm/shaitan/elliptics/cache/cache.cpp:81
#1 0x00007fc08484f13a in dnet_cmd_cache_io (backend=<optimized out>, st=0x7fbfbc0f6270, cmd=0x7fbfb007ce30, io=0x7fbfb007cea8, data=0x7fbfb007cf78 "U") at /home/buildfarm/shaitan/elliptics/cache/cache.cpp:220
#2 0x00007fc0847dea38 in dnet_process_cmd_with_backend_raw (handled_in_cache=<synthetic pointer>, data=0x7fbfb007cea8, cmd=0x7fbfb007ce30, st=0x7fbfbc0f6270, backend=0xa4ec60) at /home/buildfarm/shaitan/elliptics/library/dnet.c:954
#3 dnet_process_cmd_raw (backend=<optimized out>, st=0x7fbfbc0f6270, cmd=0x7fbfb007ce30, data=0x7fbfb007cea8, recursive=0) at /home/buildfarm/shaitan/elliptics/library/dnet.c:1045
#4 0x00007fc084b4fe32 in dnet_io_process (data_=0x7fc063cd6930) at /home/buildfarm/shaitan/elliptics/library/pool.c:1102
#5 0x00007fc084554e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6 0x00007fc0842822ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7 0x0000000000000000 in ?? ()
```

Backend disabling backtrace:
```
#0 0x00007fc084556148 in pthread_join () from /lib/x86_64-linux-gnu/libpthread.so.0
#1 0x00007fc084b50ea2 in dnet_work_pool_cleanup (place=0xa4ec78) at /home/buildfarm/shaitan/elliptics/library/pool.c:58
#2 0x00007fc0847e63c2 in dnet_backend_io_cleanup (n=0xa46750, io=0xa4ec60) at /home/buildfarm/shaitan/elliptics/library/backend.cpp:170
#3 0x00007fc0847e6e6f in dnet_backend_cleanup (node=0xa46750, backend_id=4, state=<optimized out>) at /home/buildfarm/shaitan/elliptics/library/backend.cpp:404
#4 0x00007fc0847ebfe4 in dnet_cmd_backend_control_dangerous (data=0x7fbfb0033398, cmd=0x7fbfb0033320, st=0x7fbfbc0f8c40) at /home/buildfarm/shaitan/elliptics/library/backend.cpp:626
#5 dnet_cmd_backend_control (st=0x7fbfbc0f8c40, cmd=0x7fbfb0033320, data=0x7fbfb0033398) at /home/buildfarm/shaitan/elliptics/library/backend.cpp:701
#6 0x00007fc0847ddef8 in dnet_process_cmd_without_backend_raw (data=0x7fbfb0033398, cmd=0x7fbfb0033320, st=0x7fbfbc0f8c40) at /home/buildfarm/shaitan/elliptics/library/dnet.c:859
#7 dnet_process_cmd_raw (backend=0x0, st=0x7fbfbc0f8c40, cmd=0x7fbfb0033320, data=0x7fbfb0033398, recursive=0) at /home/buildfarm/shaitan/elliptics/library/dnet.c:1043
#8 0x00007fc084b4fe32 in dnet_io_process (data_=0xa496b0) at /home/buildfarm/shaitan/elliptics/library/pool.c:1102
#9 0x00007fc084554e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007fc0842822ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x0000000000000000 in ?? ()
```

**Comment by bioothod** [comment]
Is it still relevant?

**Comment by shaitan** [comment]
Сlose, until reproduce
